### ISSUE TITLE
Purpose?

### ISSUE THREAD

**Issue by biskyt** [openeyes/OpenEyes-local-settings#1]
Hi @Vegemash - how do these files differ from those in protected/config/local.sample/ ?

We usually keep those configs up-to-date, and the installer scripts copy them into protected/config/local if the local files don't exist

**Comment by Vegemash** [comment]
Well mainly they can have branches independent of the main openeyes branch. This whole repo is mainly just to track the different default configurations for Australia, the UK, and the next place. This way differences can be tracked, cherry-picked, branched, and tested independently.

**Comment by biskyt** [comment]
Fair enough, makes sense. ABEHR has similar which we keep in our own repo, but makes sense to have them publicly available for different regions.
